const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0tuL2lxd3FENXpKcFdRUXpjMkszV2ZrakpORXBjaHp6YXhFVlJjYUgwYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZmRMRllZYVBWcldycU1lbkpVcXFJS1pYY3BweVBPRDM4MXZVaGVjbTRsND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpRUl2K3dsTjR0a21aNExBZzNyQ21SWEJ0RlMxMnVoNlcwMHF1b1FDdUVBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI5UWJORXkzU0JlY0tKOVNmdWxIYXBmd2wzcEZVQ0pEaGFBL0M0NWZkWTBnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndIaVpVc0tlY2VIaXk0bThjZXF5azA1S0gyTnBsYjdQMlVCMSswdGJaMnc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImJhTXlCcEVHaE1qT2J0SVZDS2p4UjFiUG54eHlFWEJBWWdYNnZab25kQzA9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicU1sK1MwZXdCSk15cnY5cFhKMzkyUmFGbnVvOHk3WEI3UmRUVGU3R0dHVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMDJTSE85YUZiZ2FVK24wZjdMOHd6amtMUm1JN0ZpU1NIVlFIdTd2N3F5MD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImJSTXAvVHJDOStGZjBIK0MrOTBVR29TNnlOM05pQzJreGNneW02dkxNSERUQVo2WXlQaDZqb2wvTHE5amphNkFWRzZSUkl3VHYzUXJKSDlEU20yL0FnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTU0LCJhZHZTZWNyZXRLZXkiOiJ3VWMvbUk2RlJheTJuejQ4NExmK3ozZ3NkWS9xQ25FdFpWYkNqNXU0dVM0PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6NjEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo2MSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6ZmFsc2UsImFjY291bnQiOnsiZGV0YWlscyI6IkNKM3A5bElRMmZXcnlnWVlBU0FBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJiQ0F5T0NUd2puZlE4Sk5ONVAxTDdCb255NTNycDY0bU85dktxMmpmcUZNPSIsImFjY291bnRTaWduYXR1cmUiOiJ1a3lONG14c0ErN3FXYkpOaHloNUFqYi9id1l4M0l2VEtYRmgzS05MY1k1WjNYQlpyS1NvZVNZK29NTGV1bld4N0J6SHRScTY5enRWVmNseFpxUldDUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiZ2ZJU25VQTlsV3JEYVNjWGhwSzVET1Z0U0UwcFR5OTU0NGxPa2g4cXpHbVU3UDJ1SHlZdjFYMUhSV1B1L0d1UTVYNUQ5N0JoMk1iOVh3dS9VZVJ0QVE9PSJ9LCJtZSI6eyJpZCI6IjIzNDgwODkwMDkwMTA6MkBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJBTElFTiBJSSIsImxpZCI6IjIyMDU1MzExNDM3OTcyOjJAbGlkIn0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDgwODkwMDkwMTA6MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJXd2dNamdrOEk1MzBQQ1RUZVQ5Uyt3YUo4dWQ2NmV1Smp2YnlxdG8zNmhUIn19XSwicGxhdGZvcm0iOiJzbWJpIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQUlJRFFnSSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NjY1MjE1NzMsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSU9BIiwibGFzdFByb3BIYXNoIjoiMkc0QW11In0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
